package hello;

/**
 * Created by Javier on 21/04/2016.
 */
import org.springframework.format.annotation.DateTimeFormat;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import java.sql.Time;
import java.sql.Timestamp;
import java.util.Date;

/**
 * An entity User composed by three fields (id, email, name).
 * The Entity annotation indicates that this class is a JPA entity.
 * The Table annotation specifies the name for the table in the db.
 *
 * @author netgloo
 */

@Entity
@Table(name = "usuario")
public class User {

    // ------------------------
    // PRIVATE FIELDS
    // ------------------------

    // An autogenerated id (unique for each user in the db)


    // The user's email
    @Id
    private String email;

    // The user's name
    @NotNull
    private String password;

    private String nombre;
    private String apellido1;
    private String apellido2;

    private String nick;

    private Float peso;
    private Integer estatura;

    //@DateTimeFormat(pattern="dd/MM/yyyy")
    private Timestamp fecNacimiento;


    private String codpostal;
    //1 hombre --  2 mujer
    private Integer sexo;
    private Integer activo;
    private Integer nivel;




    // ------------------------
    // PUBLIC METHODS
    // ------------------------

    public User() { }



    public User(String email, String password, String nombre, String apellido1,String apellido2, Timestamp fecNacimiento, Integer sexo) {
        this.email = email;
        this.password = password;
        this.nombre=nombre;
        this.apellido1=apellido1;
        this.apellido2=apellido2;
        this.fecNacimiento=fecNacimiento;
        this.sexo=sexo;


    }

    // Getter and setter methods


    public String getEmail() {
        return email;
    }

    public void setEmail(String value) {
        this.email = value;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getApellido1() {
        return apellido1;
    }

    public void setApellido1(String apellido1) {
        this.apellido1 = apellido1;
    }

    public String getApellido2() {
        return apellido2;
    }

    public void setApellido2(String apellido2) {
        this.apellido2 = apellido2;
    }

    public String getNick() {
        return nick;
    }

    public void setNick(String nick) {
        this.nick = nick;
    }

    public Timestamp getFecNacimiento() {
        return fecNacimiento;
    }

    public void setFecNacimiento(Timestamp fecNacimiento) {
        this.fecNacimiento = fecNacimiento;
    }

    public Float getPeso(){return peso;}

    public void setPeso(Float peso) {
        this.peso = peso;
    }

    public Integer getEstatura(){ return estatura;    }

    public void setEstatura(Integer estatura) {
        this.estatura = estatura;
    }

    public Integer getActivo() { return activo;}

    public void setActivo(Integer activo) {
        this.activo = activo;
    }

    public Integer getNivel(){ return nivel;}

    public void setNivel(Integer nivel) {
        this.nivel = nivel;
    }

    public String getCodPostal() {
        return codpostal;
    }

    public void setCodPostal(String codpostal) {
        this.codpostal = codpostal;
    }

    public Integer getSexo(){ return sexo;}

    public void setSexo(Integer sexo) {
        this.sexo = sexo;
    }


} // class User