package hello;

/**
 * Created by Javier on 21/04/2016.
 */
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import java.util.Date;

/**
 * An entity User composed by three fields (id, email, name).
 * The Entity annotation indicates that this class is a JPA entity.
 * The Table annotation specifies the name for the table in the db.
 *
 * @author netgloo
 */

@Entity
@Table(name = "usuario")
public class User {

    // ------------------------
    // PRIVATE FIELDS
    // ------------------------

    // An autogenerated id (unique for each user in the db)


    // The user's email
    @Id
    private String email;

    // The user's name
    @NotNull
    private String password;

    private String nombre;
    private String apellido1;
    private String apellido2;

    private String nick;

    private Float peso;
    private Integer estatura;

    private Date fecNacimiento;


    private String codPostal;

    private Integer tipo;
    private Integer activo;
    private Integer nivel;

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getApellido1() {
        return apellido1;
    }

    public void setApellido1(String apellido1) {
        this.apellido1 = apellido1;
    }

    public String getApellido2() {
        return apellido2;
    }

    public void setApellido2(String apellido2) {
        this.apellido2 = apellido2;
    }

    public String getNick() {
        return nick;
    }

    public void setNick(String nick) {
        this.nick = nick;
    }



    public Date getFecNacimiento() {
        return fecNacimiento;
    }

    public void setPeso(Float peso) {
        this.peso = peso;
    }

    public void setEstatura(Integer estatura) {
        this.estatura = estatura;
    }

    public void setActivo(Integer activo) {
        this.activo = activo;
    }

    public void setNivel(Integer nivel) {
        this.nivel = nivel;
    }

    public void setFecNacimiento(Date fecNacimiento) {
        this.fecNacimiento = fecNacimiento;
    }

    public String getCodPostal() {
        return codPostal;
    }

    public void setCodPostal(String codPostal) {
        this.codPostal = codPostal;
    }


    public void setTipo(Integer tipo) {
        this.tipo = tipo;
    }

    public Integer getActivo() {
        return activo;
    }




    // ------------------------
    // PUBLIC METHODS
    // ------------------------

    public User() { }



    public User(String email, String password) {
        this.email = email;
        this.password = password;


    }

    // Getter and setter methods


    public String getEmail() {
        return email;
    }

    public void setEmail(String value) {
        this.email = value;
    }



} // class User